Corrections in Terraform manifest
yandex-cloud-examples/yc-data-proc-spark-pyspark pull request #4
Opened 2024-12-12 16:25 UTC by mikhaildoc-documentat

2024-12-28 06:42 UTC, Odyvia42 requested changes

2024-12-28 06:42 UTC, Odyvia42 commented on data-proc-for-spark-jobs.tf
> +  os_sa_name             = "os-bucket-sa" # Name of the service account to manage the Object Storage bucket
```suggestion
  os_sa_name             = "os-bucket-sa" # Name of the service account to manage the Object Storage bucket and bucket's ACLs
```

2024-12-28 06:42 UTC, Odyvia42 commented on data-proc-for-spark-jobs.tf
> +        "${file(local.dp_ssh_key)}"
Здесь всё было правильно. Давай вернём как было.

2025-01-09 10:29 UTC, mikhaildoc-documentat commented on data-proc-for-spark-jobs.tf
> +        "${file(local.dp_ssh_key)}"
Тут используется не явно прописанный путь, а локальная переменная, с ней путь нужно записывать именно так, как я исправил. См. пример в https://developer.hashicorp.com/terraform/language/functions/file

2025-01-10 05:23 UTC, Odyvia42 approved these changes

2025-01-10 14:01 UTC, lanieuszko approved these changes

2025-01-10 14:01 UTC, merged